### ISSUE TITLE
Not working server

### ISSUE THREAD

**Issue by FarikLoL** [danielga/luapack#12]
![image](https://user-images.githubusercontent.com/46515364/175058799-813e451d-a73f-40d4-b995-2c290428926e.png)
I did everything according to the instructions

**Comment by FarikLoL** [comment]
![image](https://user-images.githubusercontent.com/46515364/175162368-5accfc8e-6dd1-4775-9095-5923a0e5887e.png)
I added crypto but it crashes at this moment

**Comment by danielga** [comment]
Seems like you created a loop somehow. `derma/init.lua` is not supposed to show up that many times.

**Comment by FarikLoL** [comment]
I installed luapak on a clean server

**Comment by danielga** [comment]
You say you've followed the instructions. Let's focus on this line then: `lua/send.txt must be renamed to lua/_send.txt, lua/includes/init.lua must be renamed to lua/includes/_init.lua`.
Those files you renamed are on Garry's Mod default files, not on the addon, correct?

**Comment by FarikLoL** [comment]
![image](https://user-images.githubusercontent.com/46515364/175778662-5177cb38-fb93-464c-86e9-1daf7585fc90.png)
![image](https://user-images.githubusercontent.com/46515364/175778664-527c27a3-6195-470e-861d-9404b2286a8a.png)

**Comment by danielga** [comment]
I'm unable to replicate the problem with both the latest gm_crypt and gmsv_luapack_internal releases. What branch of Garry's Mod are you using?

**Comment by FarikLoL** [comment]
not beta

**Comment by danielga** [comment]
Can you verify your files and retry the file renaming? On SteamCMD, `app_update 4020 -beta none validate` to validate the files.

**Comment by FarikLoL** [comment]
same

**Comment by danielga** [comment]
I've pushed an [update to the gmsv_luapack_internal module](https://github.com/danielga/gmsv_luapack_internal/releases/tag/1.0.2) to automate the file renaming. I've also made some small changes to this repository to remove the redundant file renaming. Please update both. If the issue persists, I don't know how to help you further.

**Comment by FarikLoL** [comment]
![image](https://user-images.githubusercontent.com/46515364/179253944-fddc2dd4-abc3-42e6-8417-947b3293b826.png)
[srcds_crash_2022_7_15T15_19_0C0.zip](https://github.com/danielga/luapack/files/9122026/srcds_crash_2022_7_15T15_19_0C0.zip)

**Comment by danielga** [comment]
This is what a clean server first startup is supposed to look like with only luapack as an addon and gm_crypt and gmsv_luapack_internal as modules.

![screenshot](https://user-images.githubusercontent.com/3681999/179257259-6288fb59-3ac0-4224-8dca-b6c29b95bfd5.png)

**Comment by danielga** [comment]
And the crash dump tells me the same I already know, there's a loop somewhere.

**Comment by FarikLoL** [comment]
everything worked
