### ISSUE TITLE
"include" does not return a value

### ISSUE THREAD

**Issue by Shark-vil** [danielga/luapack#13]
https://github.com/danielga/luapack/blob/7d602d0ae34e61c46cb246f84bb6aa1aa0a9264a/lua/luapack/cl_overrides.lua#L80-L97

---

### Wiki
https://wiki.facepunch.com/gmod/Global.include

---

### Expected
The result of the script execution ([vararg](https://wiki.facepunch.com/gmod/vararg))

---

### Now
Just compiles the code, and does not return the compilation result. There is a chance to break scripts that are dependent on the result of execution. For example:
```lua
local BaseClass = include('mod_core/classes/base_class.lua')
```

**Comment by Shark-vil** [comment]
Tell me if I'm wrong. 🤔

**Comment by danielga** [comment]
This is fixed on the `develop` branch.
