### ISSUE TITLE
gm_crypt dependency ??

### ISSUE THREAD

**Issue by avivi55** [danielga/luapack#16]
There seems to be a dependency to [gm_crypt](https://github.com/danielga/gm_crypt) but it there isn't any binaries for linux.
I'm a stupid man, is it possible to have a binary for [gm_crypt](https://github.com/danielga/gm_crypt) for linux ??

**Comment by danielga** [comment]
Please try [these builds](https://github.com/danielga/gm_crypt/releases/tag/2.1.1-rc1).
