### ISSUE TITLE
Issue when used along side Server Secure (I believe could be related to finding a file)

### ISSUE THREAD

**Issue by VaasKahnGrim** [danielga/luapack#7]
Error Recieved:
`[ERROR] gamemodes/darkrp/gamemode/init.lua:16: attempt to index global 'serversecure' (a nil value)
  1. v - gamemodes/darkrp/gamemode/init.lua:16
   2. unknown - addons/plib_v2/lua/plib/libraries/hook.lua:25
`

Other then that issue showing up server starts up perfectly with no other lua error except for when a GM hook tries to use a function inside serversecure. Other modules such as tmysql work perfectly fine however serverside.

On joining the server tho I have several files that are trying to be included in various places that are showing up as 'file not found'

My guess is some how not being able to properly recognize where the files are located?

Other then this I don't know what other information to give besides that I have verified that the send.txt is renamed to _sent.txt, the default lua/includes/init.lua is renamed to _init.lua and the serversecure.lua is in lua/includes/modules/ where it should be.

I hope this information is somewhat useful.

p.s. Thank you for the work you've done with these amazing modules

**Comment by VaasKahnGrim** [comment]
Correction to the part regarding serversecure. that error was due to me not properly putting an OS check to know if its the linux or win32 version of server secure.

the client having 'File not found' issues however does still occur when joining the server. so something related to the client for sure.

**Comment by danielga** [comment]
If it is what I think it is, it is a long standing issue with relative paths to Lua files. I'm not sure how I'll fix it since it also affects some other projects of my own.
