### ISSUE TITLE
Failed client init

### ISSUE THREAD

**Issue by michak89** [danielga/luapack#8]
Hello

I'm fighting with this sice first time opened an issue for luapack :/
Everything is set correctly for sure.

When I connect to server, everytime init fails: 

[LuaPack] Found the current pack file hash ('313C9C317B2A3E9E49AEDA1B2754D5A8309A5D2A')!
[LuaPack] Starting Lua file list build of 'download/data/luapack/313C9C317B2A3E9E49AEDA1B2754D5A8309A5D2A.dat'!

[ERROR] lua/luapack/cl_directory.lua:177: attempt to get length of local 'list' (a nil value)
  1. GetIterator - lua/luapack/cl_directory.lua:177
   2. GetSingle - lua/luapack/cl_directory.lua:156
    3. AddFile - lua/luapack/cl_directory.lua:73
     4. BuildFileList - lua/luapack/cl_core.lua:83
      5. unknown - lua/luapack/cl_core.lua:95
       6. include - [C]:-1
        7. unknown - lua/includes/init.lua:9

Couldn't include file 'derma\init.lua' (File not found) (<nowhere>)
Couldn't include file 'includes\modules\notification.lua' (File not found) (@Startup (line 1))

----->  and spam of errors here, everything no value, client init totaly dead. 

I have no more ideas, tried everything. 

:cactus: 

Server and client files are clean, no serverside errors.

**Comment by danielga** [comment]
I believe this should be fixed by the latest commits.
